management:
  security:
    enabled: false

rest:
  api:
    name: 'Spring Boot Rest Api'

redis:
  host: redis
  port: 6379
  user:
  password:

metrics:
  endpoint: http://spring-boot-rest-api:8080/metrics
