management:
  security:
    enabled: false

rest:
  api:
    name: 'Spring Boot Rest Api'

redis:
  host: localhost
  port: 6379
  user:
  password:
  timeout: 60

metrics:
  endpoint: http://localhost:8080/metrics
